apiVersion: iao.io/v1
kind: ExecutionSemantics
metadata:
  name: execution-semantics
spec:
  rootAnchorRef: "urn:iao:a:root:v2"
  namingSpecRef: "clean-final/unified-charter/naming_short.yaml"
  deterministic:
    required: true
    rules:
      - id: stable_sort_keys
        appliesTo: [yaml, json]
        mode: enforce
      - id: stable_iteration
        appliesTo: [maps, sets]
        mode: enforce
      - id: timezone_utc
        appliesTo: [timestamps]
        mode: enforce
      - id: rng_requires_seed
        appliesTo: [rng]
        mode: fail_closed
  concurrencyModel:
    model: dag_task_graph
    orderingGuarantees: [topological_order, per_task_idempotency_required]
    parallelism: { allowed: true, maxConcurrent: 8 }
    isolation: { perTask: true }
  rollbackSemantics:
    required: true
    model: snapshot_based
    rules:
      - id: rollback_refs_snapshot
        mode: enforce
      - id: rollback_verifies_health
        mode: enforce
      - id: rollback_writes_audit
        mode: enforce
  ioTyping:
    required: true
    typeSystemRef: "clean-final/unified-charter/typesystem.v2.yaml"
