apiVersion: iao.io/v1
kind: IndexingPipeline
metadata:
  name: indexing-pipeline
spec:
  inputs:
    root: "clean-final"
    includeGlobs:
      - "clean-final/**/*.yaml"
      - "clean-final/**/*.yml"
      - "clean-final/**/*.json"
      - "clean-final/**/*.md"
    excludeGlobs:
      - "clean-final/**/var/**"
  canonicalization:
    serializer: canonical_json
    yaml:
      sortKeys: true
      stripTrailingSpaces: true
      newline: "\n"
  hashing:
    algorithm: sha3-512
    contentAddressing:
      enabled: true
      tokenFormat: "iao:{kind}:{b32_24}"
      b32PrefixBytes: 15
  indexes:
    - id: id_registry
      type: content_address_registry
      output: "clean-final/unified-charter/id_registry.json"
    - id: reference_map
      type: path_ref_map
      output: "clean-final/unified-charter/reference_map.json"
    - id: semantic_merkle
      type: merkle_tree
      output: "clean-final/unified-charter/semantic_merkle.json"
    - id: search_bloom
      type: bloom_filter
      output: "clean-final/unified-charter/search_bloom.json"
  searchTokens:
    mode: deterministic
    normalize:
      lowercase: true
      splitOn: ["_", "-", ".", "/", ":", "#"]
      dropStopwords: false
