apiVersion: iao.io/v1
kind: GlobalSemanticTree
metadata:
  name: global-semantic-tree
spec:
  rootAnchorRef: "urn:iao:a:root:v2"
  nodes:
    - urn: "urn:iao:m:runtime:v1"
      path: "clean-final/runtime"
      provides: [runtime.resources, runtime.health, runtime.isolation, runtime.reclaim]
      dependsOn: []
    - urn: "urn:iao:m:obs:v1"
      path: "clean-final/observability"
      provides: [metrics.spec, alert.rules]
      dependsOn: []
    - urn: "urn:iao:m:events:v1"
      path: "clean-final/events"
      provides: [event.stream]
      dependsOn: [urn:iao:m:obs:v1]
    - urn: "urn:iao:m:log:v1"
      path: "clean-final/logging"
      provides: [logging.spec]
      dependsOn: []
    - urn: "urn:iao:m:errors:v1"
      path: "clean-final/errors"
      provides: [error.catalog, error.policy]
      dependsOn: [urn:iao:m:obs:v1, urn:iao:m:log:v1]
    - urn: "urn:iao:m:audit:v1"
      path: "clean-final/audit"
      provides: [audit.trail]
      dependsOn: [urn:iao:m:log:v1]
    - urn: "urn:iao:m:cfg:v1"
      path: "clean-final/config"
      provides: [config.signing, config.snapshot, config.diff, hot.reload]
      dependsOn: [urn:iao:m:audit:v1]
    - urn: "urn:iao:m:deploy:v1"
      path: "clean-final/deploy"
      provides: [deploy.matrix, deploy.pipeline, deploy.validation, deploy.rollback]
      dependsOn: [urn:iao:m:cfg:v1, urn:iao:m:sec:v1]
    - urn: "urn:iao:m:sec:v1"
      path: "clean-final/security"
      provides: [security.scan, secrets.reference, access.matrix, incident.response]
      dependsOn: [urn:iao:m:audit:v1]
    - urn: "urn:iao:m:test:v1"
      path: "clean-final/testing"
      provides: [test.matrix, test.data, test.plan, test.report]
      dependsOn: [urn:iao:m:deploy:v1]
    - urn: "urn:iao:m:perf:v1"
      path: "clean-final/performance"
      provides: [perf.baseline, perf.plan, perf.analysis, perf.report]
      dependsOn: [urn:iao:m:obs:v1]
    - urn: "urn:iao:m:life:v1"
      path: "clean-final/lifecycle"
      provides: [lifecycle.hooks]
      dependsOn: []
    - urn: "urn:iao:m:res:v1"
      path: "clean-final/resources"
      provides: [resource.quota, resource.scheduler, resource.gc, resource.audit]
      dependsOn: [urn:iao:m:audit:v1]
    - urn: "urn:iao:m:dep:v1"
      path: "clean-final/dependencies"
      provides: [dependency.lock, dependency.update, dependency.conflict, dependency.audit]
      dependsOn: [urn:iao:m:audit:v1]
    - urn: "urn:iao:m:docs:v1"
      path: "clean-final/docs"
      provides: [doc.gen, doc.versioning, doc.audit, doc.publish]
      dependsOn: [urn:iao:m:dep:v1]
    - urn: "urn:iao:m:sys:v1"
      path: "clean-final/system"
      provides: [system.snapshot, system.restore, system.consistency, system.signing]
      dependsOn: [urn:iao:m:cfg:v1, urn:iao:m:dep:v1]
  invariants:
    - id: rooted
      rule: "all_nodes_reachable_from_root"
      mode: fail_closed
    - id: dag
      rule: "dependencies_form_dag"
      mode: fail_closed
