apiVersion: iao.io/v1
kind: GlobalTypeSystem
metadata:
  name: global-type-system
spec:
  rootAnchorRef: "urn:iao:a:root:v2"
  namingSpecRef: "clean-final/unified-charter/naming_short.yaml"
  hash:
    algorithm: sha3-512
    boundary: canonical_type_def
    mode: fail_closed
  inheritance:
    enabled: true
    rules:
      - id: structural_subtyping
        mode: allow
      - id: field_addition_backward_compatible
        mode: allow
      - id: field_removal_breaking
        mode: deny
      - id: type_widening_breaking
        mode: deny
  types:
    - urn: "urn:iao:t:trace-id:v1"
      version: "1.0.0"
      kind: scalar
      definition:
        base: string
        constraints: { minLength: 1 }
    - urn: "urn:iao:t:ts-rfc3339:v1"
      version: "1.0.0"
      kind: scalar
      definition:
        base: string
        constraints: { format: rfc3339 }
    - urn: "urn:iao:t:ev-resource-usage:v1"
      version: "1.0.0"
      kind: object
      definition:
        required: [trace_id, resource, scope, current_value, threshold, timestamp]
        properties:
          trace_id: { $ref: "urn:iao:t:trace-id:v1" }
          resource: { type: string }
          scope: { type: string }
          current_value: { type: number }
          threshold: { type: number }
          timestamp: { $ref: "urn:iao:t:ts-rfc3339:v1" }
    - urn: "urn:iao:t:ev-policy-violation:v1"
      version: "1.0.0"
      kind: object
      definition:
        required: [trace_id, policy_id, object_ref, reason, timestamp]
        properties:
          trace_id: { $ref: "urn:iao:t:trace-id:v1" }
          policy_id: { type: string }
          object_ref: { type: string }
          reason: { type: string }
          timestamp: { $ref: "urn:iao:t:ts-rfc3339:v1" }
  bindings:
    - targetFile: "clean-final/events/event_stream.yaml"
      map:
        "spec.events[type=RuntimeResourceExceeded].payloadSchema": "urn:iao:t:ev-resource-usage:v1"
        "spec.events[type=PolicyViolationDetected].payloadSchema": "urn:iao:t:ev-policy-violation:v1"
